<?php

declare(strict_types=1);

namespace App\Controllers;

use App\Core\Controller;
use App\Core\Http;
use App\Core\Session;
use App\Models\RecurringOccurrence;
use App\Services\RecurringRuleService;
use InvalidArgumentException;
use RuntimeException;

/**
 * The recurring-transactions approval queue — the final step for a draft
 * RecurringRuleService::generateForBranch() produced. Rule CRUD and
 * generation are separate features (RecurringRuleController, the nightly
 * cron); this controller only reviews what the cron already generated.
 *
 * Thin by design: every invariant (tenant ownership, status transitions,
 * what gets posted to the ledger) lives in RecurringRuleService, the same
 * split ExpenseController/IncomeController use around TransactionService.
 */
final class RecurringOccurrenceController extends Controller
{
    /**
     * Mirrors RecurringRuleService::approveBulk()'s own cap — kept here too
     * so the flash message can say a submission was capped.
     */
    private const BULK_LIMIT = 50;

    public function index(): void
    {
        $this->view('pages/recurring-occurrences', [
            'title' => 'Recurring Approvals',
            'nav' => 'recurring-occurrences',
            'pageTitle' => 'Recurring Approvals',
            'pageMeta' => 'Drafts generated by recurring rules, waiting for review',
            'occurrences' => (new RecurringOccurrence())->pendingForBranch(),
        ]);
    }

    /**
     * Approve one draft, with whatever the reviewer edited on the form.
     * Validation mirrors ExpenseController::store()/IncomeController::store()
     * (required amount/date/description) — TransactionService::post(), called
     * inside RecurringRuleService::approve(), is the final word on whether the
     * amount is a valid positive decimal, the same as it is for a manual entry.
     *
     * @param array<string,string> $params
     */
    public function approve(array $params): void
    {
        $id = (int) ($params['id'] ?? 0);
        $back = '/recurring-occurrences';

        $clean = $this->validate([
            'amount' => 'required|max:20',
            'transaction_date' => 'required|date',
            'description' => 'required|max:255',
        ], $back);

        try {
            $transactionId = RecurringRuleService::approve($id, [
                'amount' => (string) $clean['amount'],
                'transaction_date' => (string) $clean['transaction_date'],
                'description' => (string) $clean['description'],
            ]);
        } catch (InvalidArgumentException | RuntimeException $e) {
            Session::set('_old', $_POST);
            Session::flash('error', $e->getMessage());
            Http::redirect($back);
        }

        Session::flash('success', 'Approved and posted as transaction #' . $transactionId . '.');
        Http::redirect($back);
    }

    /**
     * Reject one draft. The reason is optional free text, read the same way
     * TransactionController::void() reads void_reason — a single trimmed,
     * length-capped field that never reaches a write unvalidated in shape,
     * but does not warrant a full Validator rule set for one optional field.
     *
     * @param array<string,string> $params
     */
    public function reject(array $params): void
    {
        $id = (int) ($params['id'] ?? 0);
        $back = '/recurring-occurrences';
        $reason = trim((string) ($_POST['reject_reason'] ?? ''));

        try {
            RecurringRuleService::reject($id, $reason === '' ? null : $reason);
        } catch (RuntimeException $e) {
            Session::flash('error', $e->getMessage());
            Http::redirect($back);
        }

        Session::flash('success', 'Draft rejected. Nothing was posted to the ledger.');
        Http::redirect($back);
    }

    /** "I was away 3 months, clear the queue" — approves every selected draft as generated, no editing. */
    public function approveBulk(): void
    {
        $back = '/recurring-occurrences';

        /** @var list<mixed> $raw */
        $raw = is_array($_POST['occurrence_ids'] ?? null) ? $_POST['occurrence_ids'] : [];
        $ids = array_values(array_filter(array_map('intval', $raw), static fn (int $id): bool => $id > 0));

        if ($ids === []) {
            Session::flash('error', 'Choose at least one draft to approve.');
            Http::redirect($back);
        }

        $capped = count($ids) > self::BULK_LIMIT;
        $result = RecurringRuleService::approveBulk($ids);

        $message = $result['approved'] . ' draft(s) approved.';
        if ($result['skipped'] !== []) {
            $message .= ' ' . count($result['skipped']) . ' skipped.';
        }
        if ($capped) {
            $message .= ' Only the first ' . self::BULK_LIMIT . ' selected were processed.';
        }

        // "error" only when nothing at all went through — a partial result
        // (some approved, some skipped) is still a successful bulk action,
        // and the message above already says what was skipped and why.
        Session::flash($result['approved'] > 0 ? 'success' : 'error', $message);
        Http::redirect($back);
    }
}
